CREATE DATABASE MAYORISTA;

CREATE TABLE PRODUCTOS(
    id int PRIMARY KEY AUTO_INCREMENT NOT NULL,
    NOMBRE VARCHAR(35),
    PRECIO FLOAT NOT NULL,
    OFERTA_MERCADERIA FLOAT NOT NULL,
    UNIDAD VARCHAR (5),
    CANTIDAD VARCHAR(5)
);

INSERT INTO
    productos(NOMBRE, PRECIO, OFERTA_MERCADERIA, UNIDAD, CANTIDAD)
VALUES
    ("AZUCAR", "30000", "FLOAT NOT NULL", "10U", "1KG");

INSERT INTO
    productos (NOMBRE, PRECIO, OFERTA_MERCADERIA, UNIDAD, CANTIDAD)
VALUES
("YERBA", "14000", "9999999", "10U", "1KG");

INSERT INTO
    productos (NOMBRE, PRECIO, OFERTA_MERCADERIA, UNIDAD, CANTIDAD)
VALUES
("HARINA", "14000", "9999999", "10U", "1KG");

INSERT INTO
    productos (NOMBRE, PRECIO, OFERTA_MERCADERIA, UNIDAD, CANTIDAD)
VALUES
("ARROZ", "14000", "9999999", "10U", "1KG");

INSERT INTO
    productos (NOMBRE, PRECIO, OFERTA_MERCADERIA, UNIDAD, CANTIDAD)
VALUES
("PURE DE TOMATES", "14000", "999999", "10U", "1KG");

INSERT INTO
    productos (NOMBRE, PRECIO, OFERTA_MERCADERIA, UNIDAD, CANTIDAD)
VALUES
("FIDEOS", "14000", "9999999", "10U", "1KG");

INSERT INTO
    productos (NOMBRE, PRECIO, OFERTA_MERCADERIA, UNIDAD, CANTIDAD)
VALUES
("GASEOSAS", "14000", "9999999", "10U", "1KG");

INSERT INTO
    productos (NOMBRE, PRECIO, OFERTA_MERCADERIA, UNIDAD, CANTIDAD)
VALUES
("HARINA", "14000", "9999999", "10U", "1KG");

INSERT INTO
    productos (NOMBRE, PRECIO, OFERTA_MERCADERIA, UNIDAD, CANTIDAD)
VALUES
("ARROZ", "14000", "9999999", "10U", "1KG");

INSERT INTO
    productos (NOMBRE, PRECIO, OFERTA_MERCADERIA, UNIDAD, CANTIDAD)
VALUES
("PURE DE TOMATES", "14000", "9999999", "10U", "1KG");

INSERT INTO
    productos (NOMBRE, PRECIO, OFERTA_MERCADERIA, UNIDAD, CANTIDAD)
VALUES
("FIDEOS", "14000", "9999999", "10U", "1KG");

INSERT INTO
    productos (NOMBRE, PRECIO, OFERTA_MERCADERIA, UNIDAD, CANTIDAD)
VALUES
("GASEOSAS", "14000", "9999999", "10U", "1KG");

ALTER TABLE
    productos
ADD
    COLUMN MARCA VARCHAR (30);

UPDATE
    productos
SET
    MARCA = "LEDESMA"
WHERE
    ID = 1;

UPDATE
    productos
SET
    MARCA = "AMANDA"
WHERE
    ID = 2;

UPDATE
    productos
SET
    MARCA = "BLANCA FLOR"
WHERE
    ID = 3;

UPDATE
    productos
SET
    MARCA = "GALLO"
WHERE
    ID = 4;

UPDATE
    productos
SET
    MARCA = "PURECICA"
WHERE
    ID = 5;

UPDATE
    productos
SET
    MARCA = "LUCCHETI"
WHERE
    ID = 6;

UPDATE
    productos
SET
    MARCA = "MANAOS"
WHERE
    ID = 7;

UPDATE
    productos
SET
    MARCA = "LEDESMA"
WHERE
    ID = 1;

UPDATE
    productos
SET
    MARCA = "LEDESMA"
WHERE
    ID = 1;

UPDATE
    productos
SET
    MARCA = "LEDESMA"
WHERE
    ID = 1;

UPDATE
    productos
SET
    MARCA = "LEDESMA"
WHERE
    ID = 1;

UPDATE
    productos
SET
    MARCA = "LEDESMA"
WHERE
    ID = 1;

UPDATE
    productos
SET
    NOMBRE = "JABON EN POLVO"
WHERE
    ID = 8;

UPDATE
    productos
SET
    MARCA = "ALA"
WHERE
    ID = 8;

UPDATE
    productos
SET
    MARCA = "ALA"
WHERE
    ID = 9;

UPDATE
    productos
SET
    MARCA = "HUERTA"
WHERE
    ID = 10;

UPDATE
    productos
SET
    MARCA = "FAVORITA"
WHERE
    ID = 11;

UPDATE
    productos
SET
    MARCA = "COCA-COLA"
WHERE
    ID = 12;

UPDATE
    productos
SET
    CANTIDAD = "250G"
WHERE
    ID = 5;

UPDATE
    productos
SET
    CANTIDAD = "500G"
WHERE
    ID = 6;

UPDATE
    productos
SET
    CANTIDAD = "1,25L"
WHERE
    ID = 7;

UPDATE
    productos
SET
    CANTIDAD = "800G"
WHERE
    ID = 8;

UPDATE
    productos
SET
    CANTIDAD = "200G"
WHERE
    ID = 10;

UPDATE
    productos
SET
    CANTIDAD = "500G"
WHERE
    ID = 11;

UPDATE
    productos
SET
    CANTIDAD = "2,25L"
WHERE
    ID = 12;

UPDATE
    PRODUCTOS
SET
    OFERTA_MERCADERIA = "FLOAT NOT NULL"
WHERE
    ID = 1;